# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d82d3a1ff3f4bc3fde9d63b04f5826b7f358e71c7cc0361e67b89d60a6b16e890761a2ab61e885748a62781bb24fb86d39299cb334f91aa33a5d311d0dde341

test:
  secret_key_base: 241075ad5c672702934a99583a0ee32a30ad00f5dbebce36e92cc06de0de7f76f508c6a5e523dcf1e6bedc726b4e0957ac1155b8c3e49589f9ae62b0695c7e4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
